### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4-lab#20]
* I'm using 20.04 Ubuntu in WSL2 on Windows. The [instructions](https://github.com/antlr/antlr4-lab#building-server) say to use the "headless" version of Java (`sudo apt install openjdk-11-jre-headless`), but after doing that, the server would crash with `Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so`. It worked once I used the "normal" version `sudo apt install openjdk-11-jre`.
* I also had a problem loading some tool dependencies. I needed to add these as well: for pdfcrop, `sudo apt install texlive-extra-utils`; for pdf2svg, `sudo apt install pdf2svg`.

**Comment by parrt** [comment]
Weird!  I did headless on my ubuntu box but updating doc anyway. thanks!

```
terence_parr@lab:~$ history |grep jre
    2  apt install openjdk-11-jre-headless
    3  sudo apt install openjdk-11-jre-headless
    5  sudo apt install openjdk-11-jre-headless
  274  history |grep jre
```

I think I mentioned the others in README:

```
sudo apt install texlive-extra-utils # gets pdfcrop
sudo apt install pdf2svg
```

**Comment by kaby76** [comment]
That looks great. I'm not sure if it's required but you might want to add "-y" after the "install" in every "sudo apt install", too. E.g., "sudo apt install -y maven".

**Comment by parrt** [comment]
Ah. yep. good idea.
