### ISSUE TITLE
Allow use of local file system

### ISSUE THREAD

**Issue by teverett** [antlr/antlr4-lab#24]
It would be great to be able to point the tool to the local FS where a grammar is located and work on that grammar

**Comment by parrt** [comment]
Yeah totally. Wondered about that but might have js/browser security restrictions.  This features makes it very close to an IDE ;)

**Comment by parrt** [comment]
Maybe drag-n-drop is better than file chooser?  both?

**Comment by parrt** [comment]
Works great! But took all day to figure out that crap :(
