### ISSUE TITLE
resize bars

### ISSUE THREAD

**Issue by teverett** [antlr/antlr4-lab#25]
It would be helpful to be able to resize the different regions.  For example , the example input box is a little small.

**Comment by parrt** [comment]
main panels expand but yeah vertical scaling would be nice.

**Comment by parrt** [comment]
Seems like this link my provide some answers https://ourcodeworld.com/articles/read/994/how-to-make-an-ace-editor-instance-resizable-by-the-user-dinamically-with-a-drag-and-drop-bar

**Comment by parrt** [comment]
Wasn't quite right.
