### ISSUE TITLE
"BAD JSON RESPONSE"

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4-lab#32]
For several grammars, I'm getting "BAD JSON RESPONSE" after trying to run the parser. It looks like this is because the grammar contains actions in some target language.
* It might be best to give a better message saying that the grammar contains target-specific code.
* I think grammars-v4 requires a Java target if there is target-specific code. Is it possible to compile the java code so the grammar could be run. I.e., only allow java code from grammars-v4, and show only a read-only version of those source code?

**Comment by parrt** [comment]
Yes I've run into some weird problems. I think that the strings are encoded properly for JSON, but apparently not. I keep a log of everything so I can look into this.

I doubt I can support arbitrary code execution on the server; too much of a risk... Would be trivial to bring the server down buy some bad actor. Probably we should simply detect actions and say something about it

**Comment by kaby76** [comment]
This was just logged in StackOverflow today. https://stackoverflow.com/q/74102851/4779853

**Comment by parrt** [comment]
Just fixed.  Was a JSON issue with parse tree. Forgot you created issue. I made dup by mistake but fixed: https://github.com/antlr/antlr4-lab/issues/46
