### ISSUE TITLE
Parse tree image is cropped

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4-lab#34]
With the grammars-v4 update, I'm noticing most images are cropped. I traced this to the call to ps2pdf. The size of the image is not set for the call. The default of ps2pdf is to use the device characteristics for the server. We need to override that with the size of the PostScript image create.

The [WritePS() call](https://github.com/antlr/antlr4-lab/blob/8be8573f2ba88e7c5aa0717967dac5bc836b636d/src/org/antlr/v4/server/GrammarProcessor.java#L152) does not output the size of the image created. So, the file must be read, and the line that declares the image size used, e.g., `%%BoundingBox: 0 0 3857 414`. The values there need to be passed to [the call to ps2pdf](https://github.com/antlr/antlr4-lab/blob/8be8573f2ba88e7c5aa0717967dac5bc836b636d/src/org/antlr/v4/server/GrammarProcessor.java#L153).

    ps2pdf -dDEVICEWIDTHPOINTS=3857 -dDEVICEHEIGHTPOINTS=414 temp.ps temp.pdf

**Comment by parrt** [comment]
Ah! I saw and forgot to add issue. thanks! lemme check this out.
