### ISSUE TITLE
Proposal: Separate server and frontend

### ISSUE THREAD

**Issue by Serhioromano** [antlr/antlr4-lab#4]
Lets separate to 2 different repositories UI and server. This was it will be easier to build UI using modern technologies like React or VUE for example. With ability to automate CI\CD.

Server on the other had might be not even used while UI development as if `http://lab.antlr.org/antlr/` would work, that would be enough. Or one could clone a server repo and start it locally separately. 

Right now I would hesitate to start massive changes in UI, because there are Java files there and I do not know anything about that, and scared to break something.

**Comment by parrt** [comment]
I think I'd like to keep it all together. There's no chance I'll be moving to something complicated like React or Vue ;) there's no need as it's already working haha.

**Comment by Serhioromano** [comment]
> I think I'd like to keep it all together. There's no chance I'll be moving to something complicated like React or Vue ;) there's no need as it's already working haha.

One thing is working other thing is features. At the end it can be like jsfidle or codepen. People my share small examples as answers to questions how. There might be syntax highlight for BNF. I wanted to work on it next. Also suggestions in Parser keys that entered in Lexer and so one. The potential is so  big. Or may be even LSP generator.

**Comment by parrt** [comment]
Yes there's a lot of potential here and I appreciate your enthusiasm. :)  I already have plans to make a sharing link that people can pass around.

Simple syntax highlighting in that kind of stuff is easy and I plan to do that as well. I will start adding some feature request as issues so I can remind myself

**Comment by Serhioromano** [comment]
I see you plan to do everything yourself. Ok then.

**Comment by parrt** [comment]
I’m happy to have help but you suggested taking over completely rather than asking what I need help with

**Comment by Serhioromano** [comment]
That is because I am limited in what I can do well. I offer things I know how to do and can do best.

What is that I could help you with?

**Comment by parrt** [comment]
Hi @Serhioromano perhaps you would be interested in starting small to help me clean up?  https://github.com/antlr/antlr4-lab/issues/13

**Comment by Serhioromano** [comment]
Lets see what I can do
