### ISSUE TITLE
Input text box is being ignored in the latest online website!

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4-lab#41]
Go to lab.antlr.org and do the following:
* Start from a freshly opened browser. You can do it in different browsers, the result is the same.
* Select the "Java" grammar.
* Press "Run".
* The input is correct, but the parse tree is completely wrong, as though for some some stale input, rather than fetched directly from the control.

Go to http://134.209.209.215/ and repeat the steps. It works correctly. This is my website with my original code before the latest changes.

The input text box looks correct but the parser input is something else!

**Comment by kaby76** [comment]
I traced it down to [this code](https://github.com/antlr/antlr4-lab/blob/aa7b32d256576f498fcde728279ee997de911621/src/org/antlr/v4/server/GrammarProcessor.java#L185-L188), which returns 1, but the code just ignores the result.

Manually typing the pdfcrop command:

    root@ubuntu-s-1vcpu-512mb-10gb-nyc1-01:/tmp/antlr-images# pdfcrop --hires temp.pdf
    PDFCROP 1.40, 2020/06/06 - Copyright (c) 2002-2020 by Heiko Oberdiek, Oberdiek Package Support Group.
    !!! Error: pdfTeX run failed with value 1!

The temp.ps file looks fine, and temp.pdf also looks correct. The result of the command creates a zero-lengthed  "tmp-pdfcrop-**NNNN**.pdf" file.

I never quite understood why you call pdfcrop. That is why I removed the step because I don't think it's necessary. After removing the step, I just did "pdf2svg" of temp.pdf directly, and it produces fine svg's.

**Comment by parrt** [comment]
hmm...works for me on C. let me try java. wow. weird.  it's the crop? i did that to avoid padding to a full page I think.

**Comment by parrt** [comment]
oh. already have issue: https://github.com/antlr/antlr4-lab/issues/38

**Comment by parrt** [comment]
Just gotta add thread ID to filename.

**Comment by parrt** [comment]
Just pushed a fix.

**Comment by kaby76** [comment]
Yes, that works a lot better!
