### ISSUE TITLE
bad json response for python grammar

### ISSUE THREAD

**Issue by parrt** [antlr/antlr4-lab#51]
<img width="1465" alt="Screen Shot 2022-11-10 at 9 45 37 AM" src="https://user-images.githubusercontent.com/178777/201169649-20ec2c88-e3d4-4da7-a3d1-d71ce01e7394.png">

**Comment by kaby76** [comment]
The grammars-v4 index doesn't say what targets work, or even whether it contains target code in actions. I am writing an indexer that has all this info, and much more...copyright notices, author, date created, links to pldb.com wikipedia, code size, ... This should help the lab.antlr.org deal with certain grammars like python/python3/. And, it can be used to generate a nice webpage at https://github.com/antlr/grammars-v4.

**Comment by parrt** [comment]
Cool. Yeah, i figure this might have embedded code or something.

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4-lab/pull/59
