### ISSUE TITLE
"Can't create SVG tree; ps2pdf says: Unrecoverable error: limitcheck in .putdeviceprops"

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4-lab#64]
I'm investigating the PHP target, for https://github.com/antlr/antlr-php-runtime/issues/12. For [agc](https://github.com/antlr/grammars-v4/tree/master/agc), input [PINBALL_GAME_BUTTONS_AND_LIGHTS.agc](https://github.com/antlr/grammars-v4/blob/master/agc/examples/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc), the http://lab.antlr.org/ website outputs an error "Can't create SVG tree; ps2pdf says: Unrecoverable error: limitcheck in .putdeviceprops".

**Comment by parrt** [comment]
I ran into that when the size was too big I think. Some obscure weird error that comes from the postscript interpreter. I can't remember the exact situation that caused this, but I think it's a bug you when I worked on together.  Ah yes, i see https://github.com/antlr/antlr4-lab/issues/48

But, I don't see what it was about the "fix" that changed things:

https://github.com/antlr/antlr4-lab/commit/2a6b9a4fafa5b1228b82e0b9d9b5ad554bcfc9a8

**Comment by parrt** [comment]
This makes it sound like it was a bug back in 9.26. my mac has `GPL Ghostscript 9.53.3 (2020-10-01)`. 

Hmm...the unix box says: `GPL Ghostscript 9.50 (2019-10-15)`.

**Comment by parrt** [comment]
upgrade says on linux: `ghostscript is already the newest version (9.50~dfsg-5ubuntu4.6).`

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/antlr4-lab/commit/2a6b9a4fafa5b1228b82e0b9d9b5ad554bcfc9a8?diff=split&w=0
