### ISSUE TITLE
Example grammar for xsd regex fails to match quantifiers

### ISSUE THREAD

**Issue by richardjwilson** [antlr/antlr4-lab#70]
This is an issue in the example grammar xsd-regex (https://github.com/antlr/grammars-v4/tree/master/xsd-regex).
Curly braces, when following an atom, should be matched as a quantifier, but instead they are matched as atoms.

E.g. `x{0}` parses as 4 atoms, but should parse as one atom with a quantifier.

This can be seen when attempting to use the 'quantifier' rule to parse `{0}` in the antlr lab. The console message returned is
`1:0 mismatched input '{' expecting {'+', '?', '*', '{'}`

I believe the problem is that the curly brace characters are not listed in Char rule in the lexer grammar:

`Char : ~('.' | '\\' | '?' | '*' | '+' | '(' | ')' | '|' | '[' | ']')`

Adding these appears to resolve the issue:

`Char : ~('.' | '\\' | '?' | '*' | '+' | '(' | ')' | '|' | '[' | ']' | '{' | '}')`

**Comment by kaby76** [comment]
This sounds like a problem with the grammar. You should re-create the issue in [grammars-v4](https://github.com/antlr/grammars-v4/issues) and close [this issue](https://github.com/antlr/antlr4-lab/issues/70) out. The grammars are completely separate from the parser generator and http://lab.antlr.org/.

**Comment by richardjwilson** [comment]
Thanks Ken, apologies for posting to the wrong repo. Closing.
