### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ericvergnaud** [antlr/antlr4-lab#82]
Hi,
I notice the license for antlr4-lab is MIT whereas it is BSD 3 for antlr4.
For antlr5-lab, is it ok to switch to BSD3 ?
@parrt

**Comment by parrt** [comment]
I guess I’d be OK with it, but is it OK with the rules of licensing?

**Comment by ericvergnaud** [comment]
AFAIK you're the only author, and this stuff isn't being distributed, so I guess your agreement is good enough. Thanks !

**Comment by parrt** [comment]
Sounds good
