### ISSUE TITLE
Lab page is down?

### ISSUE THREAD

**Issue by AntoninHL** [antlr/antlr4-lab#88]
Hi,

lab.antlr.org seems to be down since many hours.
:-(

thanks for your help

**Comment by parrt** [comment]
back up. sorry. no time to debug why it crashes but this is worrying (dying in File?):

```
java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at org.antlr.v4.Tool.getImportedGrammarFile(Tool.java:790)
...
```

**Comment by AntoninHL** [comment]
Thanks for everything @parrt
