### ISSUE TITLE
ANTLR Lab is down

### ISSUE THREAD

**Issue by ar065** [antlr/antlr4-lab#91]
Appears that, yet again (according to the github issues), http://lab.antlr.org/ is down. The page appears to be loading forever since I've had it open for a little over 10 minutes now. 

I hope you manage to resolve this issue soon as it appears to be a stubborn one based on reading your comments on similar issues. 

P.S. Thank you for the work you do on ANTLR.

**Comment by parrt** [comment]
I think I figured out the issue after my latest additions to the software. It looks like it's stuck processing a request for a grammar and input, which I have squirmed away for later evaluation. For whatever reason the software is not killing threads that take too long as I intended. Anyway it's back up for now. Thanks
