### ISSUE TITLE
Any hope to sse the site up again one day?

### ISSUE THREAD

**Issue by 5cover** [antlr/antlr4-lab#94]
Is there any hope to see the Antlr Lab website up again? I've tried running as localhost.. but it's quirky, at best.

I get weird errors like:

```text
1:1 mismatched input 'eval' expecting {'assert', 'eval'}
```

Probably an encoding issue? I don't know.

**Comment by parrt** [comment]
sorry... It was up, but somebody gave it so much input it starved everybody else. It's back up after I killed it.

**Comment by kaby76** [comment]
> I get weird errors ...
Make sure you go through lexer and parser grammar panels and set them up correctly.
